JonasEthan/Delve

Gemfile.lock
app/models/character.rb
app/models/disorder.rb
app/models/enemy.rb
app/models/game.rb
app/models/journey.rb
app/models/room.rb
app/models/run.rb
db/migrate/20220530134505_add_username_to_users.rb
db/migrate/20220530134721_create_characters.rb
db/migrate/20220530135111_add_character_id_to_users.rb
db/migrate/20220530135517_create_disorders.rb
db/migrate/20220530135824_create_enemies.rb
db/migrate/20220530135933_create_games.rb
db/migrate/20220530140203_create_journeys.rb
db/migrate/20220530140245_create_runs.rb
db/migrate/20220530140356_create_rooms.rb
db/schema.rb
test/models/character_test.rb
test/models/disorder_test.rb
test/models/enemy_test.rb
test/models/game_test.rb
test/models/journey_test.rb
test/models/room_test.rb
test/models/run_test.rb

Models created, controllers following

Creating models and controllers

---

app/controllers/pages_controller.rb
app/javascript/application.js
app/javascript/controllers/test_fight.js
app/views/pages/test_fight.html.erb
config/routes.rb

Test fight works for nothing pretty bare bone and basic. Hardcoded so it exists solely as a proof/show of concept of our main game mechanic

test fight works

---

db/seeds.rb

Seeding done for our major Enemies not including the final Boss.
Also the stats are objects of change in the future

Seeding for most enemies and the Disorders

---

app/controllers/pages_controller.rb

Now our entire roster appears in the Test fight page

Now everyone it here

---

app/javascript/controllers/test_fight_controller.js

The Boss have now a bigger Damage range and they can no longer attack when defeated. Also you get a alert that you defeated the enemy with their name in it

Boss does more damage now

---

app/controllers/pages_controller.rb
app/javascript/controllers/test_fight_controller.js
app/views/pages/test_fight.html.erb

The disorders are now shown in the test fight for test purposes

Disorders now showing

---

app/javascript/controllers/test_fight_controller.js
app/views/layouts/application.html.erb

We now have a pop up alert that tells you that you entered combat

fight message

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_test_fight.scss
app/views/pages/test_fight.html.erb

Fight looks nicer now since the Images are now decently sized. Will still need some more work. But it will do as a proof of concept

img fit the screen

---

app/views/pages/test_fight.html.erb

Now the Username is shown in the Test fight scene instead of player. Only if the user is logged in

shows name now

---

db/seeds.rb

The seed file does now work with our updated database

Seed done for now

---

app/javascript/controllers/test_fight_controller.js
app/views/pages/test_fight.html.erb

Now the values HEalth and energy are represented by bars

health bars

---

app/javascript/controllers/game_framework_controller.js
app/javascript/controllers/test_fight_controller.js
app/javascript/utils/enemy_status.js
app/javascript/utils/player_status.js

Documented my code so that is easier for others to work with

document code

---

app/controllers/pages_controller.rb
app/controllers/rooms_controller.rb

Now the test fight scene is displayed with the correct enemy type

now is loaded with correct enemy type

---

app/javascript/controllers/test_fight_controller.js

The delay between the player and enemy action is now not so long anymore

now looks nicer

---

app/controllers/journeys_controller.rb

It is a quick fix so that we can only get to the amygds crossing only when atleast one Disorder is selected. But is badly coded and could cause problems later down the line

quick fix need to change later

---

app/javascript/controllers/test_fight_controller.js
app/javascript/utils/adventuring_text.js
app/views/layouts/application.html.erb

This add JS adventuring_text.js. Which is a class that will be used for the narration of the game. It will need to be updated during the next week

prework for later

---

app/controllers/pages_controller.rb
app/controllers/rooms_controller.rb
app/javascript/controllers/test_fight_controller.js
app/views/pages/test_fight.html.erb
yarn.lock

The enemies can now be fought in a row

It is now a party

---

app/javascript/utils/player_status.js
app/models/player_ability.rb
app/models/user_ability.rb
db/migrate/20220606084324_create_player_abilities.rb
db/migrate/20220606084701_create_user_abilities.rb
db/schema.rb
db/seeds.rb
test/models/player_ability_test.rb
test/models/user_ability_test.rb

The basic migration for the player abilities has been done. The seed file has now one test ability, currently hard coded but not accessible.

Migration and Seed

---

app/javascript/controllers/test_fight_controller.js
app/javascript/utils/player_status.js
app/views/pages/test_fight.html.erb

The Player ability can now be used. But still needs some finetuning and tlc for the entire system

player ability works

---

app/controllers/pages_controller.rb
app/javascript/controllers/test_fight_controller.js
app/javascript/utils/player_status.js
app/views/pages/test_fight.html.erb
package.json
yarn.lock

This set max values for the player and the enemy. But I also tried to update the images of the enemy. This does not work correctly since JS seems to have difficulties removing the child node even though on the side in the console it works. Need to figure out a fix for this

Not done yet

---

app/javascript/utils/enemy_status.js
app/models/enemy_ability.rb
db/migrate/20220606152756_create_enemy_abilities.rb
db/schema.rb
db/seeds.rb
test/models/enemy_ability_test.rb

Created the DB tables for the enemies abilities. They are not being called yet and do not have anything special happen to them

enemy abilities

---

app/assets/stylesheets/pages/_test_fight.scss
app/javascript/controllers/test_fight_controller.js
app/javascript/utils/enemy_status.js
app/models/enemy.rb
app/views/pages/test_fight.html.erb
config/environments/production.rb

This one is just the further work on the special attack frame work for the enemies. Not A Moment Respite and The Collapse

create the frame work for enemy specials

---

app/javascript/controllers/test_fight_controller.js
app/javascript/utils/enemy_status.js
app/javascript/utils/player_status.js
app/views/pages/test_fight.html.erb

Now every Enemy has one special and the bosses even have two. Now it only needs some tlc, to make if work better

each enemy has special

---

app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js
app/javascript/utils/adventuring_text.js
app/javascript/utils/enemy_status.js
app/views/pages/test_fight.html.erb

New direction in Game flow. To make a bunch of other code work easier

sweet alert kind works

---

app/controllers/pages_controller.rb
app/javascript/utils/adventuring_text.js
app/javascript/utils/enemy_status.js
app/javascript/utils/player_status.js
app/views/pages/next_room.html.erb
config/routes.rb

This is the first step for an easier approach to the game flow and game play. We will no longer rely heavily on JS we are going to change the pages now and need to parse everything as parameters now

new backend skeleton for gameplay

---

app/controllers/pages_controller.rb
app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js
app/views/pages/next_room.html.erb
app/views/pages/test_fight.html.erb

The Game Log is now a unordered List where we inject new List items into too. Some code refactoring and other stuff

game log looks nicer

---

app/controllers/pages_controller.rb
app/controllers/rooms_controller.rb
app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js
app/views/pages/test_fight.html.erb
config/routes.rb

The journeys can now be done. So far kind of boring

A journey can be done now

---

app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js
app/views/pages/test_fight.html.erb

avoids showing sweetalert on homepage and restyles game log

fixes sweetalert and updates game log

---

app/controllers/journeys_controller.rb
app/controllers/rooms_controller.rb
app/views/pages/team.html.erb

You can now play even when you are not logged in. This is just a quick fix and not a final solution in this situation. Since we say that when no one is singed in that we take the dummy user we created

quick fix for the not Logged in users

---

app/assets/stylesheets/components/_shake.scss
app/assets/stylesheets/pages/_test_fight.scss
app/views/layouts/application.html.erb
app/views/pages/test_fight.html.erb

adds shake effect on enemy
avoids wrapping of enemy and player name

adds styling to fight page

---

app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js
app/javascript/utils/player_status.js
app/views/pages/test_fight.html.erb

1. stops game log from keeping injecting text and enemy attack when player energy level is too low
2. fixes issue that player enemy  and health goes below 0%

fixes game log inject and going to negative values

---

app/controllers/journeys_controller.rb
app/controllers/pages_controller.rb
app/controllers/rooms_controller.rb
app/javascript/controllers/animation_controller.js
app/javascript/controllers/index.js
app/models/a_moments_respite.rb
app/models/journey.rb
app/models/run.rb
app/models/the_collapse.rb
app/views/layouts/application.html.erb
app/views/pages/test_fight.html.erb
db/migrate/20220608083457_create_the_collapses.rb
db/migrate/20220608083732_create_a_moments_respites.rb
db/schema.rb
test/models/a_moments_respite_test.rb
test/models/the_collapse_test.rb

This is the migration and simple creation of the a moments respite and the collapse. They are just created as of now, need to figure out how to best implement them without changing too much code around

Migrations done

---

app/assets/stylesheets/pages/_test_fight.scss
app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js

1. adds proper sweetalert popup for winning and losing
2. adds redirection to respective pages when winning or losing

adds sweetalert for win and lose on fight

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_team.scss
app/views/pages/team.html.erb
app/views/rooms/new.html.erb

adds nice layout to team page and hyperlink for donation

styles team page

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/pages/_test_fight.scss
app/views/journeys/new.html.erb
app/views/pages/test_fight.html.erb
app/views/rooms/new.html.erb

This is not the healing room but instead is the slight flavour text additions to the currently existing pages

Not healing-room yet styling

---

app/assets/stylesheets/pages/_test_fight.scss
app/javascript/controllers/animation_controller.js
app/views/pages/test_fight.html.erb

This could be a fix of the problem that the images cannot be found on heroku

possible fix

---

app/javascript/controllers/animation_controller.js
config/initializers/assets.rb

Lets see what this does. The Svgs are now all being precompiled in the assests pipeline

precompiling the svgs now

---

app/javascript/controllers/animation_controller.js
app/views/pages/test_fight.html.erb
app/views/svgs/_svg.html.erb

The image path is now with its correct timestamps

pathing now correctly

---

app/javascript/controllers/index.js
app/javascript/controllers/journeys_controller.js
app/javascript/controllers/sweet_alert_controller.js
app/views/journeys/new.html.erb

1. generates stimulus controller for journeys/new
2. deactivates submit form button unless some journey is selected

adds stimulus controller for journeys/new and deactives submit 

---

app/views/journeys/new.html.erb
app/views/journeys/repeat.html.erb

adds redirection after game based on logged in or anonymous user

---

app/assets/stylesheets/pages/_coming_soon.scss
app/controllers/pages_controller.rb
app/javascript/controllers/animation_controller.js
app/views/pages/coming_soon.html.erb
app/views/pages/home.html.erb
config/routes.rb

We now have a little "coming soon" page

coming soon

---

app/controllers/journeys_controller.rb
app/javascript/controllers/animation_controller.js
app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js
app/views/journeys/completed.html.erb
app/views/pages/test_fight.html.erb

This is just the prep for the fin page. Lena is up with styling

Rest is for you Lena

---

app/javascript/controllers/sweet_alert_controller.js
app/javascript/controllers/test_fight_controller.js
app/javascript/utils/enemy_status.js
app/javascript/utils/game_log.js
app/views/pages/coming_soon.html.erb

This adds some fixes and updates to the game logs

game log update

---

app/javascript/utils/enemy_status.js

fixes unintended popup message during enemy attack (enemy stats)

avoids unintended popup message

---

app/javascript/controllers/test_fight_controller.js
app/javascript/utils/enemy_status.js
app/javascript/utils/game_log.js
app/javascript/utils/player_status.js

Some addtions to the conditoning of the game log

fixed some of the base text

---

app/javascript/utils/game_log.js

Added some flavour text to some more enemies, not completely done yet

some more flavour text

---

app/controllers/journeys_controller.rb

Now the correct winning page gets shown

correction

---

app/javascript/utils/game_log.js

The Mask and Prosecutor now have a better game log texts

mask better fight log

---

app/javascript/controllers/animation_controller.js
app/javascript/controllers/soon_animation_controller.js
app/javascript/controllers/test_fight_controller.js

This just removes some now obsolete lines of code from our JS files

JS clean up

---

app/javascript/controllers/sweet_alert_controller.js
app/javascript/utils/game_log.js

This adds a new gameLog function that personalizes the win message for the player recording to what enemy they defeated

special win text

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_respite_room.scss
app/controllers/pages_controller.rb
app/javascript/controllers/typed_js_controller.js
app/views/pages/home.html.erb
app/views/pages/respite_room.html.erb
config/routes.rb

This is the first attempted to make the respite room work. It is for now not connected but you can visit it via typing in the right url

first vision of respite

---

app/javascript/controllers/typed_js_controller.js
app/views/pages/respite_room.html.erb
app/views/pages/test_fight.html.erb

Some slight styling alterations to the pages. Especially the gameLog container. Reconfigured the type-js to work for the situations

some slight adjustments

---

app/controllers/pages_controller.rb
app/javascript/controllers/sweet_alert_controller.js
app/views/pages/respite_room.html.erb
app/views/pages/test_fight.html.erb

The Respite room shows now up in the journey and you can continue the game from there. The room has no functionality as of yet

respite room shows up

---

app/javascript/controllers/index.js
app/javascript/controllers/respite_controller.js
app/javascript/controllers/typed_js_controller.js
app/views/pages/respite_room.html.erb

This adds the very basic function of A moments Respite room. The player can now be healed to full. No interactions with the gentleman is possible yet. Needs to be done later

basic functions

---

app/javascript/controllers/respite_controller.js
app/javascript/controllers/typed_js_controller.js
app/javascript/utils/game_log.js
app/views/pages/respite_room.html.erb

Some addition. Respite now responses to the healing action. More will follow soon

Respite heals you

---

app/views/pages/coming_soon.html.erb
app/views/pages/home.html.erb

Updated the Coming Soon page and added a Version number on the main page. We are ready to push this new Update to deploy

coming soon up to date

---

app/controllers/pages_controller.rb
app/javascript/controllers/respite_controller.js
app/javascript/utils/game_log.js
app/views/pages/respite_room.html.erb

The player can now ask the Entity who they are. It is the skeleton for the interaction frame work. Just need to add onto it

he can talk now
